language: minimal
service: docker
env:
  - DOCKER_COMPOSE_VERSION=1.25.0
before_install:
- sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname
  -s)-$(uname -m)" -o /usr/local/bin/docker-compose
- sudo chmod +x /usr/local/bin/docker-compose
install: 
- docker-compose -f udacity-c3-deployment/docker/docker-compose-build.yaml build --parallel

after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker image push "$DOCKER_USERNAME"/udacity-c3-deployment
- docker image push "$DOCKER_USERNAME"/udacity-c3-restapi-feed
- docker image push "$DOCKER_USERNAME"/udacity-c3-restapi-user
- docker image push "$DOCKER_USERNAME"/udacity-c3-frontend
